version:   "0000--17-Sep-2022"
copyright:   "2022"
author:      "ikrabhakti113"
name:        "Ikra Bhaktiananda"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/ikrabhakti113/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
